---

kind: Namespace
apiVersion: v1
metadata:
  name: tiller

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: tiller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: tiller
